"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
import jinja2
from django.templatetags.static import static
from django.urls import reverse
import importlib

# Import the config singleton
from UniqueName.config import config

# Use the app name from config
APP_NAME = config.app_name

# Import version
from version import VERSION

# Build paths inside the project like this: BASE_DIR / 'subdir',
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Main app settings. Can be overridden in the local config file
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get_config('main', 'debug', True)

# Switch so the app knows what environment to run
DEPLOYMENT_TYPE = config.get_config('main', 'deployment_type', 'dev')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get_config('main', 'secret_key', 'insecure-local-key')

# Override APP_NAME from config if specified
APP_NAME = config.get_config('main', 'app_name', APP_NAME)

# Pulled from the version.py file.
PORTAL_VERSION = f"{VERSION[0]}.{VERSION[1]}.{VERSION[2]}"

# Change this to whatever address the server is hosting at
BASE_URL = config.get_config('onea', 'base_url', 'http://127.0.0.1:5000/')

# Name of the machine to show in the footer in the base page.
ENV_NAME = config.get_config('onea', 'env_name', 'local')
# End main app settings

ALLOWED_HOSTS = []
APPLICATION_NAME = "SEEK"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    APP_NAME,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    f'{APP_NAME}.middleware.JinjaCSRFMiddleware',
]

ROOT_URLCONF = f'{APP_NAME}.urls'

def jinja2_environment(**options):
    """Configure Jinja2 environment with Django-compatible features"""
    env = jinja2.Environment(**options)
    
    # Add Django-like functions to Jinja2
    env.globals.update({
        'static': static,
        'url': reverse,
        'get_static_prefix': static,
        # Add Django's now tag equivalent
        'now': lambda format_string: __import__('datetime').datetime.now().strftime(format_string),
        # Add CSRF token support
        'csrf_input': lambda: '',  # This will be populated by middleware
        'csrf_token': lambda: '',  # This will be populated by middleware
    })
    
    # Add Django-like filters
    env.filters.update({
        'date': lambda value, format_string=None: 
            value.strftime(format_string) if format_string else value.strftime('%b %d, %Y'),
        'default': lambda value, default_value='': value if value else default_value,
        'length': len,
        'safe': lambda value: jinja2.Markup(value),
    })
    
    return env

def is_admin_template(template_name):
    """Determine if a template should be handled by Django or Jinja2"""
    # Admin templates should be handled by Django
    return template_name.startswith('admin/') or 'admin' in template_name

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            os.path.join(BASE_DIR, APP_NAME, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': f'{APP_NAME}.settings.jinja2_environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, APP_NAME, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = f'{APP_NAME}.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
ENGINE = os.environ.get('ENGINE') or config.get_config('db_config', 'db_to_use', 'pysqlite')
if ENGINE == 'pysqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': config.get_config('db_config', 'database_engine', 'django.db.backends.mysql'),
            'NAME': config.get_config('db_config', 'database_name', APP_NAME),
            'USER': config.get_config('db_config', 'database_user', 'django'),
            'PASSWORD': config.get_config('db_config', 'database_pass', 'password'),
            'HOST': config.get_config('db_config', 'database_host', '127.0.0.1'),
            'PORT': config.get_config('db_config', 'database_port', '3306'),
            'TEST': {
                'CHARSET': 'utf8',
                'COLLATION': 'utf8_unicode_ci',
                'DEPENDENCIES': []
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, APP_NAME, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
